### ISSUE TITLE
Add Classifier subtypes to Class Diagram

### ISSUE THREAD

**Issue by nemears** [nemears/uml-cafe#18]
Add the following types, some have been already added to uml-client and some have not, some might have to be filled out more:  
  - Datatype
  - PrimitiveType
  - Enumeration
  - Signals (need to make)
  - Interfaces (need to make)
 Add them to the Pallete in the class diagram, and make sure they can be seen in the specification page and element explorer. All information is within Chapter 10 of the [specification](https://www.omg.org/spec/UML/2.5.1/PDF)

**Comment by atwalder** [comment]
:)
