### ISSUE TITLE
bug: double click compartment throws 'el is undefined'

### ISSUE THREAD

**Issue by atwalder** [nemears/uml-cafe#19]
1. create a classifer diagram
2. double click on bottom portion (compartment) to view specification
3. get error :v)

**Comment by atwalder** [comment]
create an edge between diagrams and if you bottom click to connect on either (compartment) to start or end it will error out as well:
context.context.start.modelElement is undefined

**Comment by atwalder** [comment]
edges/connects messed up as it seems to be anchored to name label and looks weird when pulled below diagrams

**Comment by nemears** [comment]
Fixed all of it in this commit 1490748
