### ISSUE TITLE
bug: double click background of diagram causes error when bringing up specification

### ISSUE THREAD

**Issue by nemears** [nemears/uml-cafe#21]
right now it flashes an error about, cannot read properties of undefined id

steps to reproduce
1) create diagram
2) double click diagram, don't double click a shape or edge, just the background of the diagram
3) error should show

**Comment by atwalder** [comment]
create an edge between diagrams and if you bottom click to connect (compartment) it will error out as well:
context.context.start.modelElement is undefined

**Comment by nemears** [comment]
This was fixed with this commit 1490748
