### ISSUE TITLE
bug: weird keywordLabel positions after refresh

### ISSUE THREAD

**Issue by atwalder** [nemears/uml-cafe#32]
1. create a realization, usage, or abstraction dependency (class diagrams are horizontally aligned)
2. just refresh and it's misplaced all the way to the right not even close to edge if it's not a realization
3. if realization, after refresh just move around diagrams and the positioning is off (same for others too but you'll see weird placement right away)

**Comment by nemears** [comment]
Should be fixed with commit 4750532
